language: node_js
node_js:
- "11.1.0"
dist: trusty
sudo: false

branches:
  only:
  - app

cache:
  directories:
  - node_modules

install:
- npm i

script:
  - sh build.sh
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: app
